services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      VERSION: "1.21"
      MAX_PLAYERS: "21"
      MODE: "survival"
      MAX_MEMORY: "8G"
      SERVER_NAME: "AnneMine"
      MOTD: "Servidor de mine para a tripulação"
      ONLINE_MODE: "FALSE"
      RCON_PASSWORD: "e5624fe8"
      MODRINTH_MODPACK: "https://files.catbox.moe/5nyri1.mrpack"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data