name = "FCP - Fabric Cross Play"
author = "Lucas Oliveira (fptbb.com)"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "182fda0a98f7567e0758ba8bd44b9a4ede8bb12fc2e7de13853a05096c4b1aaf"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.x"]
