services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      VERSION: "1.21.1"
      MAX_PLAYERS: "21"
      MODE: "survival"
      MAX_MEMORY: "4G"
      SERVER_NAME: "Mine"
      ONLINE_MODE: "FALSE"
      MODRINTH_MODPACK: "https://cdn.modrinth.com/data/UFgkWMBH/versions/2jPOZtmC/FCP%20-%20Fabric%20Cross%20Play-0.1.1.mrpack"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ../../ServerData/1.21.1:/data