_default:
    @just --list

export:
    #!/usr/bin/bash
    echo "Export Modpack to pack.mrpack"
    packwiz modrinth export -o pack.mrpack

server-up:
    #!/usr/bin/bash
    echo "Starting up dev server"
    podman compose up -d

server-stop:
    #!/usr/bin/bash
    echo "Stoping dev server"
    podman compose stop

server-rm:
    #!/usr/bin/bash
    echo "Removing dev server container"
    podman compose rm -s -f
